/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "atffjlrwxgoblnaxftlm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0ZmZqbHJ3eGdvYmxuYXhmdGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxMTY5NjYsImV4cCI6MjEwMTY5Mjk2Nn0.kr9KB5p7ZQK-3EiSKOd8Ii-3MBnLaB9hm4JpzhWUOE8"